[custom]

;去广告：支持|开
;自动测速：支持|开
;微软分流：支持|开
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持

;禁止访问域名/IP列表（个人定制）
surge_ruleset=🛑 禁止访问,https://raw.githubusercontent.com/Aegon-2025/Clash/main/myLists/myBanWeb.list

;广告地址关键词列表
;surge_ruleset=🖼 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;surge_ruleset=🖼 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

;本地/局域网地址列表
surge_ruleset=↕ 直接访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list

;常用国外媒体
surge_ruleset=🎥 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
surge_ruleset=🎥 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list

;AI节点
surge_ruleset=🧠 AI节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/OpenAi.list
surge_ruleset=🧠 AI节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Gemini.list

;我的常用（国外）
surge_ruleset=🌎 国内访问,https://raw.githubusercontent.com/Aegon-2025/Clash/main/myLists/myOftenExtranet.list

;我的常用（国内）
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/Aegon-2025/Clash/main/myLists/myOftenIntranet.list

;网速测试服务器
surge_ruleset=⏱️ 网速测试,https://raw.githubusercontent.com/Aegon-2025/Clash/main/myLists/speedtest.list

;高频访问的国内域名列表（个人定制）
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CN.list
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wechat.list
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Tencent.list
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list

;高频访问的国外域名列表（个人定制）
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
surge_ruleset=🌎 国外访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list

;国内主流云服务商IP列表
surge_ruleset=🌐 国内访问,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

;国内IP地址列表（地理位置）
surge_ruleset=🌐 国内访问,[]GEOIP,CN

;未被上述规则匹配到的服务器
surge_ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,5,30
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`.*
custom_proxy_group=🎥 国外媒体`select`[]🚀 节点选择`.*`[]🛑 禁止访问
custom_proxy_group=🧠 AI节点`select`[]🚀 节点选择`.*`[]🛑 禁止访问
custom_proxy_group=⏱️ 网速测试`select`[]🌎 国外访问`[]🌐 国内访问`[]🛑 禁止访问
;custom_proxy_group=🖼 广告拦截`select`[]🛑 禁止访问`[]↕ 直接访问`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]🌎 国外访问`[]🌐 国内访问`[]🛑 禁止访问
custom_proxy_group=🌎 国外访问`select`[]🚀 节点选择`[]↕ 直接访问`[]🛑 禁止访问
custom_proxy_group=🌐 国内访问`select`[]↕ 直接访问`[]🚀 节点选择`[]🛑 禁止访问
custom_proxy_group=↕ 直接访问`select`[]DIRECT
custom_proxy_group=🛑 禁止访问`select`[]REJECT

enable_rule_generator=true
overwrite_original_rules=true
